project:
  type: website
  output-dir: docs

website:
  title: " "
  description: "Welcome to The Upside-Down blog, a place where paradox and mystery come alive in the light of the Gospel."
  reader-mode: true
  site-url: https://theupsidedownblog.netlify.app
  favicon: img/round_logo2.png
  google-analytics: "G-V3QQ28RRMM"
  navbar: 
    pinned: true
    collapse: true
    logo: img/tud_logo2.png
    left:
      - text: "Home"
        href: index.qmd
      - text: "English"
        menu: 
          - text: "Blog"
            href: eng/index.qmd
          - text: "Purpose"
            href: eng/about.qmd
          - text: "Remarks"
            href: eng/remarks.qmd
          - text: "References"
            href: eng/refers.qmd
      - text: "Español"
        menu: 
          - text: "Blog"
            href: esp/index.qmd
          - text: "Propósito"
            href: esp/about-esp.qmd
          - text: "Observaciones"
            href: esp/observaciones.qmd
          - text: "Referencias"
            href: esp/refers-esp.qmd
      - text: "Articles"
        menu: 
          - text: "Truth & Grace"
            href: articles/truth_grace.qmd
          - text: "Tune His Frequency"
            href: articles/tune_his_freq.qmd
            
    right:
      - icon: person
        href: https://ocardec.netlify.app
        target: _blank
      - icon: envelope-at
        href: "mailto:admin@theupsidedownblog.com" 
        
    # tools:
    #   - icon: github
    #     menu:
    #       - text: Source Code
    #         href:  https://github.com/ocardec/theupsidedownblog
    #         target: _blank
    #       - text: Report a Bug
    #         href:  https://github.com/ocardec/theupsidedownblog/issues/new/choose
    #         target: _blank
  search:
      location: navbar
      type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&nbsp;&nbsp;Powered by <a href="https://www.navtheway.com" target="_blank">&nbsp;Navigate the Way</a></span>
    
    right: |
      <span class="faux-block">&#169; Copyright 2025, Cardec Solutions
format:
  html: 
    page-layout: article
    fontsize: 1.1em
    theme: 
        dark: darkly 
        light: flatly
    css: styles.css



