project:
  type: website
  output-dir: docs

website:
  title: " "
  description: "Welcome to The Upside-Down blog, a place where paradox and mystery come alive in the light of the Gospel."
  reader-mode: true
  site-url: https://theupsidedownblog.netlify.app
  favicon: images/round_logo2.png
  google-analytics: "G-V3QQ28RRMM"
  navbar: 
    pinned: true
    collapse: true
    logo: images/tud_logo2.png
    left:
      - text: "Home"
        href: index.qmd
      - text: "English"
        menu: 
          - text: "Blog"
            href: eng/index.qmd
          - text: "Purpose"
            href: eng/about.qmd
      - text: "Español"
        menu: 
          - text: "Blog"
            href: esp/index.qmd
          - text: "Propósito"
            href: esp/about-esp.qmd
      - text: "References"
        href: eng/refers.qmd
    right:
      - icon: person
        href: https://ocardec.netlify.app
        target: _blank
      - icon: envelope-at
        href: "mailto:admin@theupsidedownblog.com" 
      - icon: twitter
        href: https://x.com/CardO37474
        target: _blank
        
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/ocardec/theupsidedownblog
            target: _blank
          - text: Report a Bug
            href:  https://github.com/ocardec/theupsidedownblog/issues/new/choose
            target: _blank
  search:
      location: navbar
      type: textbox
  page-footer: 
    left: |
      <div class="bmc-button-container">
        <script type="text/javascript" src="https://cdnjs.buymeacoffee.com/1.0.0/button.prod.min.js" data-name="bmc-button" data-slug="ocardec" data-color="#252525" data-emoji=""  data-font="Lato" data-text="Buy me a coffee" data-outline-color="#ffffff" data-font-color="#ffffff" data-coffee-color="#FFDD00" >
        </script>
        <style>
          .bmc-button-container .bmc-button {
            font-size: 10px !important; 
            background-color: transparent !important;
            border: none; 
          }
        </style>
      </div>
    center: |
      <span class="faux-block">Created in &nbsp; <a href="https://quarto.org" target="_blank"><img src="images/quarto.png" width="70"></a></span>
      <span class="faux-block">&nbsp;&nbsp;Powered by <a href="https://www.navtheway.com" target="_blank">&nbsp;NTW</a></span>
    right: |
      <span class="faux-block">&#169; Copyright 2024, Cardec Solution
format:
  html: 
    page-layout: article
    fontsize: 1.1em
    theme: 
        dark: darkly
        light: flatly
    css: styles.css



