project:
  type: website
  output-dir: ../_docs/esp
  
website:
  # reader-mode: true
  title: ""
  description: "¡Bienvenidos al blog invertido, un lugar donde la paradoja y el misterio se desarrollan a la luz del Evangelio."
  # site-url: https://theupsidedownblog.netlify.app
  favicon: /images/round_logo2.png
  # google-analytics: "G-V3QQ28RRMM"
  navbar: 
    # pinned: false
    # collapse: true
    logo: /images/round_logo2.png
    left:
      - text: "Inicio"
        href: ../index.qmd
      - text: "Información"
        menu: 
          - text: "Descripción"
            href: about-esp.qmd
          - text: "Autor"
            href: https://ocardec.netlify.app
            target: _blank
      - text: "Referencias"
        href: refers-esp.qmd
    right:
      - text: "English"
        href: ../eng/index.qmd
      - text: "Español"
        href: index.qmd
      - icon: envelope-at
        text: Email
        href: "mailto:admin@theupsidedownblog.com"  
  search:
      location: navbar
      type: textbox
  page-footer: 
    left: |
      <div class="bmc-button-container">
        <script type="text/javascript" src="https://cdnjs.buymeacoffee.com/1.0.0/button.prod.min.js" data-name="bmc-button" data-slug="ocardec" data-color="#252525" data-emoji=""  data-font="Lato" data-text="Cómprame un café" data-outline-color="#ffffff" data-font-color="#ffffff" data-coffee-color="#FFDD00" >
        </script>
        <style>
          .bmc-button-container .bmc-button {
            font-size: 10px !important; 
            background-color: transparent !important;
            border: none; 
          }
        </style>
      </div>
    center: |
      <span class="faux-block">Creado en &nbsp; <a href="https://quarto.org" target="_blank"><img src="images/quarto.png" width="70"></a></span>
      <span class="faux-block">&nbsp;&nbsp;Propulsado por <a href="https://www.navtheway.com" target="_blank">&nbsp;NTW</a> </span>
    right: |
      <span class="faux-block">&#169; Derechos 2024, Cardec Solution
format:
  html: 
    page-layout: article
    fontsize: 1.0em
    theme: 
        dark: darkly
        light: flatly
    css: styles.css
#editor: source
