---
title: "¡Bienvenidos al Blog Invertido!"
listing:
  sort: "date desc"
  type: grid
  contents: posts/esp
  fields: [image, date, title, reading-time, categories]
  page-size: 9
  categories: true
  sort-ui: false
  filter-ui: false
page-layout: article
title-block-banner: true
---

**El Reino de Dios no es lo que el mundo espera...**

Este, torna nuestras suposiciones al revés y desafía nuestra comprensión del poder, la importancia y el éxito. Donde el mundo exalta a los orgullosos, Cristo nos llama a la humildad; donde la cultura glorifica la fuerza, el Evangelio celebra la debilidad. Jesucristo mismo es la encarnación de esta paradoja, reinando como el Rey que fue crucificado, logrando la victoria a través de la entrega y ofreciendo vida a través de Su propia muerte.

En el reino invertido de Dios, los últimos son los primeros, los más pequeños son los más grandes, y los humildes son exaltados. Aquí, la luz conquista la oscuridad, la vida triunfa sobre la muerte, y la cruz, que antes era un símbolo de vergüenza, se convierte en la piedra angular de la esperanza y la salvación. Este blog invertido existe para explorar y celebrar las profundas y paradójicas verdades que definen el Reino de Dios. Busca invitar a los lectores a abrazar los caminos contra-intuitivos y contra-culturales de Jesús en un mundo que cada vez está mas desesperado por encontrar significado y vida.

<br/>

------------------------------------------------------------------------

<br/>

<link rel="icon" type="image/png" href="images/tud_logo2"/>
